version: "3"
services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500

  grpc-server:
    image: vatsan127/grpc_server
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    deploy:
      replicas: 2

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - grpc-server
    volumes:
      - ./nginx-conf/conf:/etc/nginx/conf.d

  grpc-client:
    image: vatsan127/grpc_client
    depends_on:
      - grpc-server
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=6565
    deploy:
      replicas: 1
    command: ["7"]

