version: "3"
services:
  consul:
    image: hashicorp/consul
    depends_on:
      - grpc-server
    ports:
      - "8500:8500"
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500

  grpc-server:
    image: grpc_server
    networks:
      - grpc-network
    deploy:
      replicas: 1

  grpc-client:
    image: vatsan127/grpc_client
    depends_on:
      - grpc-server
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=6565
    deploy:
      replicas: 1
    command: [ "7" ]

  nginx:
    image: nginx:latest
    depends_on:
      - grpc-server
    volumes:
      - C:\nginx-1.25.4\conf:/etc/nginx/conf.d
    ports:
      - 6565:6565
    networks:
      - grpc-network

networks:
  grpc-network:

